# Generated by Django 5.2.12 on 2026-03-21 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_month', models.DateField(unique=True)),
                ('generated_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-payroll_month',),
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('work_email', models.EmailField(max_length=254)),
                ('employment_type', models.CharField(max_length=32)),
                ('department', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('date_of_joining', models.DateField()),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('annual_leave_allowance', models.PositiveIntegerField(default=0)),
                ('annual_leave_used_before_month', models.PositiveIntegerField(default=0)),
                ('monthly_leave_cap', models.PositiveIntegerField(default=0)),
                ('total_calendar_days', models.PositiveIntegerField(default=0)),
                ('active_calendar_days', models.PositiveIntegerField(default=0)),
                ('working_days', models.PositiveIntegerField(default=0)),
                ('holidays_in_month', models.PositiveIntegerField(default=0)),
                ('present_days', models.PositiveIntegerField(default=0)),
                ('approved_leave_days', models.PositiveIntegerField(default=0)),
                ('approved_paid_leave_days', models.PositiveIntegerField(default=0)),
                ('approved_lwp_days', models.PositiveIntegerField(default=0)),
                ('unapproved_lwp_days', models.PositiveIntegerField(default=0)),
                ('total_lwp_days', models.PositiveIntegerField(default=0)),
                ('monthly_compensation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('per_day_deduction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gross_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_decision', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='hr.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ('full_name',),
                'unique_together': {('run', 'employee')},
            },
        ),
    ]
