# Generated by Django 5.2.12 on 2026-03-21 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(editable=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('employment_type', models.CharField(choices=[('employee', 'Employee'), ('intern', 'Intern'), ('consultant', 'Consultant'), ('freelancer', 'Freelancer')], max_length=32)),
                ('reports_to_name', models.CharField(blank=True, max_length=255)),
                ('work_summary', models.TextField()),
                ('supporting_file', models.FileField(blank=True, null=True, upload_to='attendance/%Y/%m/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.employee')),
            ],
            options={
                'ordering': ('-attendance_date', '-submitted_at'),
                'constraints': [models.UniqueConstraint(fields=('employee', 'attendance_date'), name='unique_employee_daily_attendance')],
            },
        ),
    ]
