name: Deploy Inditech HR to EC2 via SSM

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::736616688306:role/GitHubActionsInditechHRDeployRole
          aws-region: ap-south-1

      - name: Deploy using SSM
        run: |
          aws ssm send-command 
            --instance-ids "i-042b772db54dd2178" 
            --document-name "AWS-RunShellScript" 
            --comment "Deploy Inditech HR" 
            --parameters commands=[
              "cd /var/www/Inditech-HR",
              "git pull origin main",
              "/var/www/.venv/bin/pip install -r requirements.txt",
              "/var/www/.venv/bin/python manage.py migrate",
              "/var/www/.venv/bin/python manage.py collectstatic --noinput",
              "sudo systemctl restart inditech-hr"
            ]
